# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5127c4a529f809a1db37a8b5d008290"
name = "PH Checkout UI"
handle = "ph-checkout-ui"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "kandy-test-site.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
