# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
name = "Banner Timer"
handle = "banner-timer"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"
[[extensions.targeting]]
module = "./src/Header.tsx"
target = "purchase.checkout.header.render-after"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
# --------------- Container ----------------
[[extensions.settings.fields]]
key = "background"
type = "single_line_text_field"
name = "Background"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["transparent", "base", "subdued"]'

[[extensions.settings.fields]]
key = "border"
type = "single_line_text_field"
name = "Border"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "base", "dashed", "dotted"]'

[[extensions.settings.fields]]
key = "borderWidth"
type = "single_line_text_field"
name = "Border Width"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["base", "medium", "thick"]'

[[extensions.settings.fields]]
key = "borderRadius"
type = "single_line_text_field"
name = "Border Radius"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "small", "base", "large", "fullyRounded"]'

[[extensions.settings.fields]]
key = "blockAlignment"
type = "single_line_text_field"
name = "Vertical Alignment"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["start", "center", "end"]'

[[extensions.settings.fields]]
key = "spacing"
type = "single_line_text_field"
name = "Spacing"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "extraTight", "tight", "base", "loose", "extraLoose"]'


# --------------- Padding ----------------
[[extensions.settings.fields]]
key = "padding_block"
type = "single_line_text_field"
name = "Padding Block"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "extraTight", "tight", "base", "loose", "extraLoose"]'

[[extensions.settings.fields]]
key = "padding_inline"
type = "single_line_text_field"
name = "Padding Inline"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "extraTight", "tight", "base", "loose", "extraLoose"]'

# --------------- Details ----------------
[[extensions.settings.fields]]
key = "icon_source"
type = "single_line_text_field"
name = "Icon Image URL"

[[extensions.settings.fields]]
key = "icon_width"
type = "number_integer"
name = "Icon Width"
[[extensions.settings.fields.validations]]
name = "min"
value = "10"
[[extensions.settings.fields.validations]]
name = "max"
value = "80"

[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"

[[extensions.settings.fields]]
key = "text"
type = "multi_line_text_field"
name = "Description Text"

[[extensions.settings.fields]]
key = "time"
type = "number_integer"
name = "Time in seconds"
description = "Ex.: 900 - 15 minutes."
