# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
name = "Upsell Simple"
handle = "upsell-simple"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "heading_title"
type = "single_line_text_field"
name = "Heading Title"
description = "Enter a heading title for the upsell"

[[extensions.settings.fields]]
key = "title"
type = "single_line_text_field"
name = "Title"
description = "Enter a title for the upsell"

[[extensions.settings.fields]]
key = "description"
type = "multi_line_text_field"
name = "Description"
description = "Enter a description for the upsell"

[[extensions.settings.fields]]
key = "image"
type = "single_line_text_field"
name = "Image"
description = "Paste the image url here for the upsell"

[[extensions.settings.fields]]
key = "price"
type = "single_line_text_field"
name = "Custom Price"
description = "Enter a custom price for the upsell. FORMAT: '499' will be '$4.99'"

[[extensions.settings.fields]]
key = "compare_price"
type = "single_line_text_field"
name = "Custom Compare Price"
description = "Enter a custom compare price for the upsell. FORMAT: '499' will be '$4.99'"

[[extensions.settings.fields]]
key = "percentage_text"
type = "single_line_text_field"
name = "Percentage Text"
description = "Enter the text for the percentage e.g. '% off'"

[[extensions.settings.fields]]
key = "button_text"
type = "single_line_text_field"
name = "Button Text"
description = "Enter the text for the button"

[[extensions.settings.fields]]
key = "variant"
type = "variant_reference"
name = "Variant"
description = "Select the variant you want to upsell"

# --------------- Display Settings ----------------

[[extensions.settings.fields]]
key = "show_heading"
type = "boolean"
name = "Show Heading"
description = "Show the heading for the upsell"

[[extensions.settings.fields]]
key = "show_description"
type = "boolean"
name = "Show Description"
description = "Show the description for the upsell"

[[extensions.settings.fields]]
key = "show_price"
type = "boolean"
name = "Show Price"
description = "Show the price for the upsell"

[[extensions.settings.fields]]
key = "show_compare_price"
type = "boolean"
name = "Show Compare Price"
description = "Show the compare price for the upsell"

[[extensions.settings.fields]]
key = "show_save_percentage"
type = "boolean"
name = "Show Save Percentage"
description = "Show the save percentage for the upsell"

[[extensions.settings.fields]]
key = "save_percentage_inline"
type = "boolean"
name = "Save Percentage Inline"
description = "Show the save percentage inline for the upsell"

[[extensions.settings.fields]]
key = "prices_above_description"
type = "boolean"
name = "Prices Above Description"
description = "Show the prices above the description for the upsell"

# --------------- Container ----------------

[[extensions.settings.fields]]
key = "background"
type = "single_line_text_field"
name = "Background"
description = "Select the background color for the Container"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["transparent", "base", "subdued"]'

[[extensions.settings.fields]]
key = "border"
type = "single_line_text_field"
name = "Border"
description = "Select the border color for the Container"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "base", "dashed", "dotted"]'

# --------------- Padding ----------------
[[extensions.settings.fields]]
key = "padding_block"
type = "single_line_text_field"
name = "Padding Block"
description = "Select the padding block for the Container"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "extraTight", "tight", "base", "loose", "extraLoose"]'

[[extensions.settings.fields]]
key = "padding_inline"
type = "single_line_text_field"
name = "Padding Inline"
description = "Select the padding inline for the Container"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "extraTight", "tight", "base", "loose", "extraLoose"]'
