# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-01"

[[extensions]]
name = "Image Block"
handle = "image-block"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"
[[extensions.targeting]]
module = "./src/Header.tsx"
target = "purchase.checkout.header.render-after"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "source"
type = "single_line_text_field"
name = "Image URL"

[[extensions.settings.fields]]
key = "source_mb"
type = "single_line_text_field"
name = "Image URL (Mobile)"

[[extensions.settings.fields]]
key = "inline_size"
type = "number_integer"
name = "Image Width"
[[extensions.settings.fields.validations]]
name = "min"
value = "100"
[[extensions.settings.fields.validations]]
name = "max"
value = "1200"

[[extensions.settings.fields]]
key = "inline_size_mb"
type = "number_integer"
name = "Image Width (Mobile)"
[[extensions.settings.fields.validations]]
name = "min"
value = "100"
[[extensions.settings.fields.validations]]
name = "max"
value = "800"

[[extensions.settings.fields]]
key = "inline_position"
type = "single_line_text_field"
name = "Image Alignment"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["start", "center", "end"]'

[[extensions.settings.fields]]
key = "padding_block"
type = "single_line_text_field"
name = "Padding Block"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "extraTight", "tight", "base", "loose", "extraLoose"]'

[[extensions.settings.fields]]
key = "padding_inline"
type = "single_line_text_field"
name = "Padding Inline"
[[extensions.settings.fields.validations]]
name = "choices"
value = '["none", "extraTight", "tight", "base", "loose", "extraLoose"]'
